QA284 part1 (C1518+C1519)
ElKalinin/JoinBetTests pull request #10
Opened 2022-12-17 11:06 UTC by ElKalinin

2022-12-19 13:51 UTC, JavaScriptonit requested changes
@ElKalinin Все проверки запросов работают кроме теста C1518
В основном минорные комменты для исправления
Отличная работа!

2022-12-19 13:51 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/registration/email/emailRegistration.cy.js
> +            cy.get('@emailRegister').should('not.be.called');
@ElKalinin проверь тест, у меня тесты проходят при успешной регистрации. Приходит респонс emailRegister и ошибки нет
<img width="1408" alt="292" src="https://user-images.githubusercontent.com/73838525/208434105-bca241da-6a08-440f-a760-8b94cbabdda2.png">

2022-12-19 13:51 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/registration/email/emailRegistration.cy.js
> +            }
@ElKalinin сможешь вынести все эти проверки в отдельный файл? 
Конструкция выглядит громоздко и удобнее было бы вызывать проверку на каждую query отдельно в необходимый момент + все эти проверки переиспользуются часто в тестах и как другие переменные/команды/функции хранятся в отдельных файлах.
В проекте этот тесты выглядит вот так:

![293](https://user-images.githubusercontent.com/73838525/208439540-3cdb191b-5ef4-4e32-9469-259070b445ba.png)

2022-12-21 19:47 UTC, ElKalinin commented on cypress/fixtures/selectors/index.js
> +     */
done

2022-12-21 19:50 UTC, ElKalinin commented on cypress/fixtures/selectors/index.js
> +        modalWindow: '[aria-label="sign-up"]', // модальное окно регистрации
Разбил на части, где в том числе есть окно подтверждения пройденности регистрации! МодалВиндоу- это селектор самой формы.

2022-12-21 19:50 UTC, ElKalinin commented on cypress/fixtures/selectors/index.js
> +        closeWindow: '[aria-label="bonus popup close"]', // Закрытие модального окна
Done

2022-12-21 19:50 UTC, ElKalinin commented on cypress/support/utils/reg/index.js
> +    cy.get(header.window3.closeWindow, {timeout: 60000}).click({force: true});
Done

2022-12-21 19:51 UTC, ElKalinin commented on cypress/fixtures/translations/navigation/header/index.js
> +        errorMessageEmail: 'Введите email',
Done. Разбил отдельно для почты и телефона.

2022-12-21 19:51 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/registration/email/emailRegistration.cy.js
> +    langsHeader.forEach(({lang, headerCurrency, errorMessageEmail}) => {
Done

2022-12-21 19:55 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/registration/email/emailRegistration.cy.js
> +            cy.get('@emailRegister').should('not.be.called');
Не совсем понял суть вопроса! У меня оповещение показывает и показывает, что ЕмэйлРегистэ не вызывался!
<img width="570" alt="image" src="https://user-images.githubusercontent.com/112701291/208992096-704aff12-abb0-4d88-9625-636abcdb789c.png">

2022-12-21 19:57 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/registration/email/emailRegistration.cy.js
> +            }
Здесь есть вопросы, как лучше это сделать! Т.к.совпадающих условий не так много

2022-12-21 20:05 UTC, ElKalinin commented
В тесте С5402 выявился баг на сайте - не появляется сообщение!

2022-12-22 09:41 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/registration/email/emailRegistration.cy.js
> +            cy.get('@emailRegister').should('not.be.called');
@ElKalinin Об этом и речь. Посмотри мой скрин - там emailRegister должен вызываться и регистрация пройдена, открыта модалка регистрации ШАГ 2, но в консоли оповещение показывает, что ЕмэйлРегистэ не вызывался!

2022-12-22 09:51 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/registration/email/emailRegistration.cy.js
> +            }
@ElKalinin на звонке обсудим

2023-01-09 19:41 UTC, merged