Changes after error
ElKalinin/JoinBetTests pull request #2
Opened 2022-09-22 22:57 UTC by ElKalinin

add new Part 1 of Test QA213 version made with Andrew add new comment in test
delete DS_Store
add .gitignore and test.md
update QA-213_Part1.cy.js file
add commit with new name of file
add new comment in test
delete DS_Store
add .gitignore and test.md
update QA-213_Part1.cy.js file
add commit with new name of file

2022-09-23 17:39 UTC, JavaScriptonit submitted a review, later dismissed
@ElKalinin Отличная работа для 1го ПР. Долго пушили и коммитили и наконец переходим к ревью. Предлагаю сделать немного исправлений в рамках этой ветки (этого ПР) и исходя из этого делать уже дальше 2ой ПР

2022-09-23 17:39 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/QA213__Patr1.cy.js
> +            .should('be.visible')
@ElKalinin Твои тесты не падают и находят необходимые селекторы 👍, но есть вопросы к
архитектуре тестов. Посмотри, пожалуйста, [Text Content
](https://docs.cypress.io/guides/references/assertions#Text-Content)

Не буду писать решение, опишу пошагово проверку:
1) Cypress находит по селектору 1 элемент или группу элементов
2) Cypress проверяет что у элемента есть текст
3) Cypress проверяет текст на соответствие

В твоём случае Cypress находит элемент по содержанию текста. Таким образом можно пропустить ошибки в вёрстке, например, текст 'Лайв' может быть у другого элемента, а тест будет успешно пройден.

2022-09-23 17:39 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/QA213__Patr1.cy.js
> +        cy.get('[class="Menu_root__P08M2"]').contains('Киберспорт')
@ElKalinin у тебя в тестах должны быть 24 отдельных селектора вместо 1 - '[class="Menu_root__P08M2"]'
Не рекомендую обращаться к элементу по классу, так как он динамический. Если другого варианта нет - можно обрезать его чтобы тесты потом не падали - '[class^="Menu_root"]'
[Дока](https://webdevtips.pro/css/30-must-know-css-selectors/)
Попробуй найти span через ссылку, например.

2022-09-23 17:39 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/QA213__Patr1.cy.js
> +    it('Column 1',()=>{
@ElKalinin предлагаю сразу называть describe и it логически из того что тестируем, например:

```suggestion
describe('Casino. Footer', () => {
    it('Отображение всех текстовых данных - язык ru', () => {
```

2022-09-24 08:45 UTC, Artem-Perminov requested changes
добавить в gitignore: 
```
node_modules/
.idea/
coverage
```

2022-09-27 22:50 UTC, ElKalinin commented
@JavaScriptonit @Artem-Perminov Обновил файл QA213_Part1.cy.js 
Мне на него ссылку нужно сделать?

2022-10-02 10:56 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +// Hi,guys!
удалить эту строку

2022-10-02 10:57 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +
удалить лишнюю пустую строку

2022-10-02 11:02 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +import { footertitles } from '../../../fixtures/arrays/footer';
некорректное название переменной, нужно использовать всегда lowerCamelCase, здесь можно почитать инфу - [lowerCamelCase](https://skillbox.ru/media/code/notatsii-v-programmirovanii/)

итого должно быть так: footerTitles

2022-10-02 11:04 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +
удалить лишнюю строку, между import и describe должна быть 1 пустая строка: 

```
import { footer } from '../../../fixtures/selectors';
import { footertitles } from '../../../fixtures/arrays/footer';

describe('Casino. Footer.',()=> {
```

2022-10-02 11:07 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +
тоже лишняя строка, надо так: 

```
describe('Casino. Footer.',()=> {
    beforeEach(() => {
        cy.visit('https://qa-gdjsmns.hk/ru/sportsbook/home', {
            auth: {
                username: 'joinbet',
                password: 'ajvxeASUkr'
            }
        })
    })
```

2022-10-02 11:08 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +
лишнии строки вверху и внизу: 

```
it('Отображение всех текстовых данных - язык ru', () => {
        cy.get(footer.links.rates).contains('Ставки').should('have.text', footertitles.titles.ratestitle)
        cy.get(footer.links.line).should('have.text', footertitles.titles.linetitle)
        cy.get(footer.links.live).should('have.text', footertitles.titles.livetitle)
        cy.get(footer.links.cybersport).should('have.text', footertitles.titles.cybersporttitle)
        cy.get(footer.links.statistics).should('have.text', footertitles.titles.statisticstitle)
        cy.get(footer.links.results).should('have.text', footertitles.titles.resultstitle)
        cy.get(footer.links.casino).contains('Казино').should('have.text', footertitles.titles.casinotitle)
        cy.get(footer.links.slots).should('have.text', footertitles.titles.slotstitle)
        cy.get(footer.links.livecasino).should('have.text', footertitles.titles.livecasinotitle)
        cy.get(footer.links.news).should('have.text', footertitles.titles.newstitle)
        cy.get(footer.links.topgames).should('have.text', footertitles.titles.topgamestitle)
        cy.get(footer.links.jackpots).should('have.text', footertitles.titles.jackpotstitle)
        cy.get(footer.links.info).contains('Информация').should('have.text', footertitles.titles.infotitle)
        cy.get(footer.links.about).should('have.text', footertitles.titles.abouttitle)
        cy.get(footer.links.privacy).should('have.text', footertitles.titles.privacytitle)
        cy.get(footer.links.faq).should('have.text', footertitles.titles.faqtitle)
        cy.get(footer.links.amlkyc).should('have.text', footertitles.titles.amlkyctitle)
        cy.get(footer.links.responsiblegambling).should('have.text', footertitles.titles.responsiblegamblingtitle)
        cy.get(footer.links.bonuses).contains('Бонусы').should('have.text', footertitles.titles.bonusestitle)
        cy.get(footer.links.welcomebonus).should('have.text', footertitles.titles.welcomebonustitle)
        cy.get(footer.links.terms).should('have.text', footertitles.titles.termstitle)
        cy.get(footer.links.useful).contains('Полезное').should('have.text', footertitles.titles.usefultitle)
        cy.get(footer.links.payments).should('have.text', footertitles.titles.paymentstitle)
        cy.get(footer.links.bettingpolicy).should('have.text', footertitles.titles.bettingpolicytitle)
    })
```

2022-10-02 11:11 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        cy.get(footer.links.rates).contains('Ставки').should('have.text', footertitles.titles.ratestitle)
.contains - убрать, никогда не используй .contains - это ненадежно, ставишь корректный селектор и сразу should
```
cy.get(footer.links.rates).should('have.text', footertitles.titles.ratestitle)
```

2022-10-02 11:24 UTC, Artem-Perminov requested changes

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        cy.get(footer.links.casino).contains('Казино').should('have.text', footertitles.titles.casinotitle)
.contains - убрать

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        cy.get(footer.links.info).contains('Информация').should('have.text', footertitles.titles.infotitle)
.contains - убрать

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        cy.get(footer.links.bonuses).contains('Бонусы').should('have.text', footertitles.titles.bonusestitle)
.contains - убрать

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        cy.get(footer.links.useful).contains('Полезное').should('have.text', footertitles.titles.usefultitle)
.contains - убрать

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/fixtures/arrays/footer/index.js
> +export const footertitles = {
переписать на lowerCamelCase footerTitles

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/fixtures/arrays/footer/index.js
> +        ratestitle: 'Ставки',
тоже самое lowerCamelCase, ratesTitle

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/fixtures/arrays/footer/index.js
> +    }
во всем файле изменить название переменных на lowerCamelCase

2022-10-02 11:24 UTC, Artem-Perminov commented on cypress/fixtures/selectors/index.js
> +
удалить лишнюю пустую строку вверху

2022-10-06 12:17 UTC, Artem-Perminov approved these changes

2022-10-07 10:46 UTC, merged