add test for link navigation in footer
ElKalinin/JoinBetTests pull request #3
Opened 2022-10-13 09:42 UTC by ElKalinin

2022-10-13 14:15 UTC, Artem-Perminov requested changes
cy.request смотри нужны ещё проверки на 200 статус по каждой линке

2022-10-13 14:15 UTC, Artem-Perminov commented on cypress/fixtures/url/footer/index.js
> +    'https://st2-gdjsmns.hk/ru/sportsbook/home',
лучше убрать портянку http и т.д. все ссылки должны быть такого формата
```
 `/sportsbook/home`
```
+ это сокращает код 
+ ты не зависишь от языка, тесты будут работать под любым VPN любой страны и локали
+ будут работать на всех стендах

2022-10-13 14:15 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +                        cy.url().should('eq', urls[index])
лучше
```
include вместе eq
```

2022-10-19 09:40 UTC, JavaScriptonit approved these changes
@ElKalinin привет! Согласен с комментариями Артёма.
Ты будешь делать правки в этом ПР или пока что оставляем так ?

2022-10-20 16:07 UTC, ElKalinin commented
@JavaScriptonit Все пункты кроме кода 200 подчищены- не могу разобраться с реквестом на нашем сайте- из-за 401й ошибки не работает.. failOnStatusCode: false не помог

2022-10-20 18:13 UTC, JavaScriptonit requested changes
@ElKalinin запросил правки, см комментарии

2022-10-20 18:13 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +                it('Переход по ссылкам', () => {
@ElKalinin Дружище, проверь, пожалуйста, отступы.
У меня твои describe'ы уехали вправо...

2022-10-26 10:17 UTC, merged