final version of TestQA243
ElKalinin/JoinBetTests pull request #6
Opened 2022-11-15 09:42 UTC by ElKalinin

2022-11-15 19:59 UTC, Artem-Perminov requested changes

2022-11-15 19:59 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
>              cy.wait(3000)
В рамках последних комментариев Саши cy.wait (имеется ввиду ожидание времени без действий) мы больше не используем, — Саша подтвердил, что это плохая практика. Попробуй без него, а если не получится, отметь, пожалуйста, в коде комментарий, что нужно будет убрать, — чуть позже расскажем как

2022-11-15 19:59 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
>          cy.wait(3000)
убрать cy.wait

2022-11-15 19:59 UTC, Artem-Perminov commented on cypress/fixtures/selectors/index.js
> +        groups: '[role="group"]', // группы бонусов
ненадежные селекторы типа ```'[role="group"]'``` и т.д. - сейчас на проекте мы используем 2 типа селекторов:

1. вяжемся к aria-label="что-то", а если таких элементов нет, то 2 вариант
2. через классы, типа ```'[class*="Banner_root"]'```

проще говоря, надо сделать всё по аналогии с regBonus - там валидно

2022-11-15 19:59 UTC, Artem-Perminov commented on cypress/support/commands.js
> +Cypress.Commands.add('status200',(url)=>{
Ого, вот это здорово Илюх, сам придумал?
@JavaScriptonit Андрюх, можно что-то подобное в боевом проекте замутить ```cy.status200(element)```

2022-11-15 19:59 UTC, Artem-Perminov commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +                    cy.status200(element)
класс, красава

2022-11-16 09:30 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
>          cy.wait(3000)
Убрал- работает!

2022-11-16 09:34 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +                    cy.status200(element)
Вам спасибо!)

2022-11-17 09:17 UTC, Artem-Perminov approved these changes

2022-11-17 12:00 UTC, JavaScriptonit commented on cypress/support/commands.js
> +Cypress.Commands.add('status200',(url)=>{
@Artem-Perminov Согласен. Такого рода функции надо в команды переводить.
Илья в будущем может сделать аудит нашего проекта и перевести все функции в команды если это подходит по логике

2022-11-17 12:05 UTC, JavaScriptonit approved these changes
@ElKalinin Все комментарии посмотрел и код. Всё сделано отлично :+1:

2022-11-19 12:22 UTC, merged