QA264 - currency list check
ElKalinin/JoinBetTests pull request #7
Opened 2022-11-22 08:16 UTC by ElKalinin

2022-11-22 09:52 UTC, JavaScriptonit requested changes
@ElKalinin Изменения в рамках текущего ПР - комментарии.
Отпиши, пожалуйста, ответными комментариями если решено или если есть вопросы

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +            .click()
@ElKalinin здесь предлагаю обойтись 1 вложенностью:
```suggestion
        cy.get(header.regButton)
            .click()
```
Так как header - это отдельный блок и в нём уже выделить разные элементы:
regButton
entryButton
profileButton
и тд

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +                .click();
@ElKalinin здесь предлагаю вынести регистрацию в отдельный блок, так как это уже отдельная модалка (отдельная фича):
```suggestion
            cy.get(reg.window1.currencyItem)
                .click();
```

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +    it('Проверка списка валют', () => {
```suggestion
    it(`Проверить список валют в дропдауне "Валюта"` , () => {
```
Название взять из Тест-рейл для всех авто-тестов

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        });
1) проверить что список имеет длину аналогичную твоему заготовленному массиву/объекту с валютами. 
.should('have.length', array.length)
2) проверить что каждый элемент массива соответствует названию:
cy.get($el).should('have.text', array[index]);
3) проверить помимо текста загрузку картинок валют и их кол-во (было ранее)
4) проверить текст на 3х языках (было ранее)

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/fixtures/selectors/index.js
> +    },
вяжемся к дата-элементу или классу:
```suggestion
currencyNameList: '[class^="CurrencySelect_item"]', // 16 валют из списка
```

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/fixtures/selectors/index.js
> +        closeButton: '[class="HeaderModal_close___E9yg"]',
@ElKalinin не вяжемся целиком к классу, хвостик меняется
Берёт только статичную часть

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/fixtures/selectors/index.js
> +        closeButton: '[class="HeaderModal_close___E9yg"]',
написал в тестах по поводу изменения вложенности

2022-11-22 09:52 UTC, JavaScriptonit commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        cy.get(header.registrationButton.openButton)
@ElKalinin после открытия модалок регистрации / авторизации - открывается модалка регистрации / авторизации по **Телефону**
Пропущен шаг перехода на **Почту**

cy.get(reg.window1.regEmailButton).click();

2022-11-22 15:18 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +            .click()
cделано

2022-11-22 15:19 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +    it('Проверка списка валют', () => {
Сделано

2022-11-24 13:50 UTC, ElKalinin commented on cypress/fixtures/selectors/index.js
> +    },
сделано

2022-11-24 13:51 UTC, ElKalinin commented on cypress/fixtures/selectors/index.js
> +        closeButton: '[class="HeaderModal_close___E9yg"]',
сделано

2022-11-24 13:51 UTC, ElKalinin commented on cypress/fixtures/selectors/index.js
> +        closeButton: '[class="HeaderModal_close___E9yg"]',
сделано

2022-11-24 16:38 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        cy.get(header.registrationButton.openButton)
сделал

2022-11-24 16:38 UTC, ElKalinin commented on cypress/e2e/0-JoinBet/footer/footer.cy.js
> +        });
сделано

2022-11-25 12:35 UTC, JavaScriptonit approved these changes
@ElKalinin Отличная работа!
По всем комментариям отработал на 100%

Есть небольшие уточнения, но это уже архитектура и это сейчас не критично.
При написании тестов на проекте - будет разделение тестов в регистрацию по почте/телефону в разные файлы и объединять тесты не нужно, будем их в разные файлы разделять. Вернёмся к этому позже

2022-11-26 21:08 UTC, merged